# syntax=docker/dockerfile:1.20

FROM --platform=$BUILDPLATFORM golang:1.26.6-alpine3.23@sha256:e57c41c1d5864341031181b0db34b9a537bb5773eb6428e4e5bdaea0f9135406 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS="$TARGETOS" GOARCH="$TARGETARCH" \
    go build -buildvcs=false -trimpath -ldflags='-s -w' -o /out/nps ./cmd/nps


FROM alpine:3.23@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /nps

COPY --from=builder /out/nps /nps/nps
COPY web /nps/web
COPY conf/nps.conf conf/clients.json conf/hosts.json conf/tasks.json \
    conf/server.pem conf/server.key /nps/conf/

VOLUME ["/nps/conf"]
STOPSIGNAL SIGTERM

ENTRYPOINT ["/nps/nps"]
